#!/bin/bash
# Pull HireLoop runtime config (Secrets Manager + SSM) and write a flat
# dotenv file consumed by docker-compose `env_file:`.
#
# Re-run safely: rewrites the file each call, picks up rotated secrets without
# instance replacement. Invoked from EC2 user-data on first boot and from the
# `deploy-sse` GitHub Actions job before `docker compose up`.
#
# Required: aws-cli v2, python3, IAM permissions to GetSecretValue on the
# 7 hireloop/${env}/* secrets and to GetParameter on /hireloop/${env}/* + the
# shared /hireloop/shared/* SSM tree.

set -euo pipefail

ENVIRONMENT="${ENVIRONMENT:-dev}"
REGION="${AWS_REGION:-us-east-1}"
OUTPUT_FILE="/opt/hireloop/.env.secrets"

mkdir -p "$(dirname "$OUTPUT_FILE")"

fetch_secret_key() {
  local secret_name="$1"
  local json_key="$2"
  aws secretsmanager get-secret-value \
    --secret-id "$secret_name" \
    --region "$REGION" \
    --query SecretString \
    --output text \
  | python3 -c "import json,sys; print(json.loads(sys.stdin.read())['$json_key'])"
}

fetch_ssm() {
  local name="$1"
  aws ssm get-parameter \
    --name "$name" \
    --region "$REGION" \
    --query 'Parameter.Value' \
    --output text
}

DB_PASSWORD=$(fetch_secret_key "hireloop/${ENVIRONMENT}/db-app-password" "password")
ANTHROPIC_API_KEY=$(fetch_secret_key "hireloop/${ENVIRONMENT}/anthropic-api-key" "key")
GOOGLE_API_KEY=$(fetch_secret_key "hireloop/${ENVIRONMENT}/google-api-key" "key")
STRIPE_SECRET_KEY=$(fetch_secret_key "hireloop/${ENVIRONMENT}/stripe-secret-key" "key")
STRIPE_WEBHOOK_SECRET=$(fetch_secret_key "hireloop/${ENVIRONMENT}/stripe-webhook-secret" "key")
INNGEST_EVENT_KEY=$(fetch_secret_key "hireloop/${ENVIRONMENT}/inngest-event-key" "key")
INNGEST_SIGNING_KEY=$(fetch_secret_key "hireloop/${ENVIRONMENT}/inngest-signing-key" "key")

DB_ENDPOINT=$(fetch_ssm "/hireloop/${ENVIRONMENT}/db/endpoint")
COGNITO_USER_POOL_ID=$(fetch_ssm "/hireloop/${ENVIRONMENT}/cognito/user-pool-id")
COGNITO_CLIENT_ID=$(fetch_ssm "/hireloop/${ENVIRONMENT}/cognito/user-pool-client-id")
ASSETS_BUCKET=$(fetch_ssm "/hireloop/${ENVIRONMENT}/s3/assets-bucket-name")

umask 077
cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by hireloop-fetch-env.sh — do not edit
ENVIRONMENT=${ENVIRONMENT}
DATABASE_URL=postgresql+asyncpg://hireloop_${ENVIRONMENT}_app:${DB_PASSWORD}@${DB_ENDPOINT}:5432/hireloop_${ENVIRONMENT}?ssl=require
REDIS_URL=redis://redis:6379
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY}
INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY}
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
COGNITO_REGION=${REGION}
COGNITO_JWKS_URL=https://cognito-idp.${REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
AWS_S3_BUCKET=${ASSETS_BUCKET}
DISABLE_PAYWALL=false
EOF

chmod 600 "$OUTPUT_FILE"
echo "wrote $OUTPUT_FILE ($(wc -l < "$OUTPUT_FILE") lines)"
